ccgus/fmdb

src/fmdb/FMDatabase.m

`[FMDatabase FMDBUserVersion]` still reported `2.3` instead of `2.4` as specified in the podspec.

Correct reported FMDB version

---

FMDB.podspec
Tests/FMDatabaseFTS3WithModuleNameTests.m
fmdb.xcodeproj/project.pbxproj
src/extra/fts3/FMDatabase+FTS3.h
src/extra/fts3/FMDatabase+FTS3.m

Most of the time when using FTS, you'll only need to use a single tokenizer. This change simplifies using a single tokenizer.
@newyankeecodeshop, could you check this out as well?

Don't force custom tokenizer module name

---

FMDB.podspec

Any chance you'd be willing to create a new tag version with the changes in master? We need to create a new CocoaPod version of FMDB for people to have access to everything that's changed since last September.
Here's the list of changes since v2.4:
* Cleanup
* Correct reported FMDB version
* Don't force custom tokenizer module name
* Quick fix, thanks to @kangchuh
* Fixes wrong handling of sqlite3_column_bytes(...).
According to the official documentation of SQLite the order in which you call sqlite3_column_bytes and sqlite3_column_blob (and the related methods to retrieve the stored value) is important:
"In other words, you should call sqlite3_column_text(), sqlite3_column_blob(), or sqlite3_column_text16() first to force the result into the desired format, then invoke …

Updated podspec version to prepare for v2.5 tag

---

src/fmdb/FMDatabase.h

Whoops. I noticed, while reviewing the updated class reference documentation, that I put the note regarding `FMDatabaseVariadic.swift` on the wrong method (I didn't put it on `executeQuery`, like I intended). Fixed that. Also updated my pull request on the documentation, accordingly.

Fix note in executeQuery documentation

---

src/fmdb/FMDatabase.m

Fix warning: Implicit conversion changes signedness: 'unsigned int' to 'int'

Update FMDatabase.m to fix implicit signedness conversion

---

src/fmdb/FMDatabase.m

I use `FMDatabase` in many iOS applications and I've analyzed my projects with Facebook Infer (http://fbinfer.com/). The analyze returned two warnings with `block` parameters that could be null.
This little commit just check if `block` variable is not null before calling it.

Check if block parameter is not null (after Facebook Infer analyze)

---

FMDB.podspec

The `unicode61` tokenizer is now enabled by default and the `sqlite3/unicode61` subspec is deprecated.
`FMDB/standalone` should depend on `sqlite3/fts` instead.
I also updated the comment to make it clearer that the most recent stable version of
SQLite is built and used if the standalone subspec is selected, not a custom prebuilt
version.
I am the [sqlite3 podspec](https://github.com/clemensg/sqlite3pod) maintainer and am trying to keep the sqlite3 pod as close
to the [official stable release schedule](https://www.sqlite.org/news.html) as possible. Delays should be a few days max.
Signed-off-by: Clemens Gruber <clemensgru@gmail.com>

Replace deprecated unicode61 dependency and improve comments

---

src/fmdb/FMDatabase.m

If FMDB is embedded in a project with the `-Wall` & `-Wextra` ‘Other warning flags’ enabled the unused parameters in these methods and the extra semicolon raise warnings at build time.

Compiler warning cleanup for extra flags.

---

README.markdown

The Swift example in README was referencing `println` and was using a deprecated `stringByAppendingPathComponent`. I've updated it for both of those issues.

Updated README for Swift 2 changes

---

FMDB.podspec

I use fmdb/SQLCipher (Xcode7)and got warnings like this when program run:
```
WARNING: Requested sleep of 65 milliseconds, but SQLite returned 1000. Maybe SQLite wasn't built with HAVE_USLEEP=1?
```
I found the warning message in line 237 of FMDatabase.m:
```
int requestedSleepInMillseconds = arc4random_uniform(50) + 50;
int actualSleepInMilliseconds =
sqlite3_sleep(requestedSleepInMillseconds);
if (actualSleepInMilliseconds != requestedSleepInMillseconds) {
NSLog(@"WARNING: Requested sleep of %i milliseconds, but
SQLite returned %i. Maybe SQLite wasn't built with HAVE_USLEEP=1?",
requestedSleepInMillseconds, actualSleepInMilliseconds);
}
return 1;
```
and in line 33239 of sqlite3.m
```
/
static int unixSleep(sqlite3_vfs *NotUsed, int microseconds){
#if OS_VXWORKS
struct timespec sp; …
```

Added HAVE_USLEEP=1 to fmdb/SQLCipher

---

src/extra/fts3/FMDatabase+FTS3.m
src/extra/fts3/fts3_tokenizer.h

I moved the inclusion of the file "sqlite3.h" from src/extra/fts3/fts3_tokenizer.h to src/extra/fts3/FMDatabase+FTS3.m because of a compilation error when using fmdb/fts on pods using frameworks ...
sorry for the branch name ...

swift framework compatibility when using FTS 3

---

CHANGES_AND_TODO_LIST.txt
README.markdown
Tests/Tests-Info.plist
fmdb.xcodeproj/project.pbxproj
fmdb.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme
src/fmdb/FMDatabase.h
src/fmdb/FMDatabase.m

These renditions are `executeQuery:values:error:` and `executeUpdate:values:error:`.
Updated README, which has Swift 2 example, accordingly.

Add renditions of executeQuery and executeUpdate that throw Swift errors

---

fmdb.xcodeproj/project.pbxproj

This commit updates project settings to support building and referencing the FMDB and FMDB-IOS static libs by including the project in a workspace rather than via cocoa pods.  These two commits expose the base FMDB headers as public and adds a copy headers step such that headers can be included as <FMDB/*.h>.

Project file updates to support inclusion of FMDB via including the project in a workspace.

---

FMDB.podspec
src/extra/fts3/FMDatabase+FTS3.h
src/fmdb/FMDatabase.h
src/fmdb/FMDatabasePool.h
src/fmdb/FMDatabaseQueue.h
src/fmdb/FMResultSet.h

This PR addresses some build issues I encountered when working with the latest CocoaPods and the Xcode 7.2 beta. The compiler is becoming much stricter about non-modular imports and some things in the project that previously worked began throwing errors. Here is a rundown of the changes:
1. I eliminated the `common` subspec entirely because it failed to build during lint. The issue is that since it did not declare a dependency on either the SQLite standalone or pull in the `sqlite3` library it could not build (symbol errors for SQLite). I simply inlined the `source_files` and `exclude_files` at the appropriate places. This has the added benefit of reducing `pod spec lint` times for the project because there’s one less subspec to be built for all targets (watchOS, tvOS, iOS, OS X).
2. I …

Rework SQLite dependency imports and Podspec structure

---

CHANGES_AND_TODO_LIST.txt
FMDB.podspec
README.markdown
Tests/FMDatabaseAdditionsTests.m
Tests/FMDatabaseQueueTests.m
Tests/FMDatabaseTests.m
Tests/FMResultSetTests.m
fmdb.xcodeproj/project.pbxproj
fmdb.xcodeproj/xcshareddata/xcschemes/FMDB MacOS.xcscheme
fmdb.xcodeproj/xcshareddata/xcschemes/FMDB iOS.xcscheme
src/extra/Swift extensions/FMDatabaseVariadic.swift
src/fmdb/FMDB.h
src/fmdb/FMDatabase.h
src/fmdb/FMDatabase.m
src/fmdb/FMDatabaseAdditions.h
src/fmdb/FMDatabaseAdditions.m
src/fmdb/FMDatabasePool.h
src/fmdb/FMDatabasePool.m
src/fmdb/FMDatabaseQueue.h
src/fmdb/FMDatabaseQueue.m
src/fmdb/FMResultSet.h
src/fmdb/FMResultSet.m
src/fmdb/Info.plist

Gus, here is version 2.6 pull request, which introduces framework support (akin to that of the `swiftFrameworks` branch, though with even more modest changes), as well as taking it the next step and introducing Carthage support (i.e. added two shared targets that build MacOS and iOS frameworks, respectively). I tried to update the change log to indicate the nature of the non-backward compatible change, but if you think we need something more explicit, let me know.
I haven't touched the Cocoapods stuff (other than bumping version), so perhaps we need someone more familiar with Cocoapods take a look at that.
I also haven't touched the static library targets (I'd vote for removing them to eliminate confusion, but that's your call). I'd also suggesting removing the command line target and …

Framework and Carthage Support

---

src/extra/fts3/FMDatabase+FTS3.h
src/extra/fts3/FMDatabase+FTS3.m

- `CFStringGetBytes` was calculating the UTF-8 offset from the beginning of string to current token again and again for each token. The longer the document the longer this operation took. Most tokenizers are sequential, and this repeated calculation was unnecessary
- Started caching last token range and its UTF-8 offset to avoid this repeated calculation.
- Extremely long documents (1 million characters) could take 30-40 seconds to index on a fast machine. Now they are indexed in less than a second
- Non-sequential tokenizers are still supported: cached range is reset if a token does not follow previous token.

Improve FTS tokenization performance

---

FMDB.podspec

fts3_tokenizer.h only needs to be included privately by
FMDatabase+FTS3.m so we can exclude it from the umbrella header.
cc @newyankeecodeshop

Allow FTS to be compiled as Swift framework

---

src/fmdb/FMDatabase.m

Avoids the warning:
"Several methods with selector 'close' of mismatched types are found for the @selector expression"

Fix mismatched-selectors warning

---

src/fmdb/FMDatabasePool.h
src/fmdb/FMDatabasePool.m
src/fmdb/FMDatabaseQueue.h
src/fmdb/FMDatabaseQueue.m

FMDatabasePool can now be subclassed to use a subclass of FMDatabase.
FMDatabasePool initializer now accepts a custom vfsName.

Added support for custom database class and vfsName

---

FMDB.podspec

It looks like Cocoapods is not more restrictive about how default_subspecs is used.  In order to continue supporting alternative builds with the latest sqlite3 and FTS this pull request gets rid of the nested subspecs.  Instead of 'standalone' with 'default' and 'FTS' nested within, the pod spec now contains two alternative subspecs for 'standalone' and 'standalone-fts'.

Resolves default_subspecs error in podfile.

---

src/fmdb/FMDatabase.h
src/fmdb/FMDatabase.m
src/fmdb/FMDatabaseQueue.h
src/fmdb/FMDatabaseQueue.m

Marek Serafin's [cbc4188] was previously applied, but the changes were silently removed in [59f8d63]. This reapplies those changes. 
(Theoretically this should be a cherrypick, but I ended up in an hourlong fight with git over it which I think are related to whitespace changes between the 2014 commit and now).

Re-add the ability to interrupt a query in progress

---

src/fmdb/FMDatabase.h
src/fmdb/FMDatabase.m

Pursuant to issue https://github.com/ccgus/fmdb/issues/535, we may want to expose `sqlite3_extended_errcode`.
Also, unrelated, updated notes for variadic `FMDatabase` methods, to remove the advise to add the variadic extension. Better to just use `executeQuery:values:`, IMHO.

Expose `sqlite3_extended_errcode`

---

src/fmdb/FMDatabase.m
src/fmdb/FMResultSet.m

This fixes compilation warnings appearing since Xcode 8 due to deprecated Garbage collection support.

Feature-conditional statements for `-finalize` method to opt-out GC methods when using ARC

---

src/fmdb/FMDatabaseQueue.m

Compilation warning: `unused variable `**`currentSyncQueue`**
I've rather used `#ifndef NDEBUG` clause because neither `DEBUG` nor `NDEBUG` need to be defined in the environment and `assert()` is effectively defined the same way in `assert.h`.

Patched minor compilation warning for NDEBUG-defined builds

---

README.markdown

Notably, in `inTransaction`, in Swift 3:
- the parameters are optionals (because FMDB has not yet been audited for nullability) and
- `memory` has been replaced with `pointee`.
These changes are pursuant to issue https://github.com/ccgus/fmdb/issues/562.

Update README for Swift 3

---

fmdb.xcodeproj/project.pbxproj

Allow using FMDB in an application extension by setting the flag APPLICATION_EXTENSION_API_ONLY to YES.

Set APPLICATION_EXTENSION_API_ONLY to YES

---

src/fmdb/FMDatabaseQueue.h

All the initialisers in the FMDatabaseQueue.h are annotated as returning non nil instances via the NS_ASSUME_NONNULL_BEGIN declaration at the top of the header, yet if you check their implementation (also the documentation comments) they can return nil.
This PR fixes the nullability annotations for the initializers of the FMDatabaseQueue class.

Fixed nullability annotations for various FMDatabaseQueue initializers.

---

Tests/FMDatabaseTests.m
src/fmdb/FMDatabase.h
src/fmdb/FMDatabase.m
src/fmdb/FMDatabasePool.h
src/fmdb/FMDatabasePool.m
src/fmdb/FMDatabaseQueue.h
src/fmdb/FMDatabaseQueue.m

Prior to FMDB 2.7, I could implement these as categories on `FMDatabase`* classes. Now, most of the internals are no longer exposed in a way that would allow this. This PR seeks to contribute these categories back to FMDB (and allows upgrading code that relied on these categories), which allows using immediate-type transactions as well as running WAL checkpoint (all of these on the FMDatabaseQueue specifically) operations.
Thanks for your consideration!

Added support for immediate transactions and checkpoint

---

Tests/FMDatabaseTests.m
src/fmdb/FMDatabase.h
src/fmdb/FMDatabase.m

`FMDatabase` was previously checking `_db` to determine whether the opening of a database was successful or not. But that's not a valid assumption. If you had previously attempted to open a database and it failed, _it still returns a `sqlite*` pointer._ As the [`sqlite_open` documentation](http://sqlite.org/c3ref/open.html) says (emphasis added):
> _Whether or not an error occurs_ when it is opened, resources associated with the [database connection](http://sqlite.org/c3ref/sqlite3.html) handle should be released by passing it to [sqlite3_close()](http://sqlite.org/c3ref/close.html) when it is no longer required.
The reason this is important is that if an `openWithOptions` failed (e.g. opening from application support directory without `SQLITE_OPEN_CREATE` option), you want to be able to …

Fix isOpen logic

---

Tests/FMDatabaseQueueTests.m
src/fmdb/FMDatabase.m
src/fmdb/FMDatabaseQueue.m

- If you call `[db close]`, it should reset `isOpen` to false;
- When you try to use `[queue database]`, it should not only check that the `FMDatabase` is non-`nil`, but also whether the database `isOpen` or not;
- Added `testClose` test to `FMDatabaseQueue` logic if the queue's `FMDatabase` was closed.

Refine close logic

---

src/sample/main.m

Allows sample code to compile via Xcode 9.2 targeting macOS.

Fix for 'This function declaration is not a prototype'.

---

src/fmdb/FMDatabaseAdditions.h
src/fmdb/FMDatabaseAdditions.m

The schema functions return the result of calling `-[FMDatabase executeQuery:withArgumentsInArray:orDictionary:orVAList:]`
Since `-[FMDatabase executeQuery:withArgumentsInArray:orDictionary:orVAList:]` can return nil on error, the type annotation of these functions should match that.
The function doc also mentions that this function can return nil:
>  @return `FMResultSet` of schema; `nil` on error.
This is important for Swift, as attempting to access a nil result which is currently typed as `FMResultSet` (instead of `FMResultSet?) will crash.

Update nullability annotations for `-[FMDatabase getSchema]` and `-[FMDatabase getTableSchema]`

---

Tests/FMDatabaseTests.m
src/fmdb/FMDatabase.m

`-[FMDatabase executeStatements:withResultBlock:]` method has potential crash bugs, for setting nil object as NSMutableDictionary value

-[FMDatabase executeStatements:withResultBlock:] method crash

---

src/fmdb/FMDatabase.m
src/fmdb/FMDatabasePool.m
src/fmdb/FMDatabaseQueue.m

In Xcode 10, if the `__attribute__((noescape))` is present in the header file,
it must also be present in the implementation.
I have verified that all targets build and all unit tests pass.

Added attributes to method implementations

---

src/fmdb/FMDatabase.h

Passing in nil resets the FMDB to use a default unix date format. At the moment calling
this method with nil raises a warning in Xcode because it is marked as nonnull
because of the NS_ASSUME_NONNULL_BEGIN marcro.
This commit marks it correctly as _Nullable.

Mark the setDateFormat method's parameter as _Nullable

---

Tests/FMDatabaseAdditionsTests.m
src/fmdb/FMDatabase.m
src/fmdb/FMDatabaseAdditions.m
src/fmdb/FMDatabasePool.m
src/fmdb/FMDatabaseQueue.m

For apps that include FMDB source in their Xcode projects (instead of linking against the framework), it may be nice to place all of FMDB's localized strings in their own strings table instead of having them pollute the global Localizable.strings table.

Use NSLocalizedStringFromTable

---

src/fmdb/FMDatabase.m

`
if (errmsg && [self logsErrors]) {
NSLog(@"Error inserting batch: %s", errmsg);
sqlite3_free(errmsg);
}
`
`errmsg` leaks here, if `logsErrors` is false.

Fix errmsg leaks

---

.gitignore
Package.swift

Add very basic Swift Package Manager support.
It only builds the library target.
#750

Add SPM manifest with a library target

---

FMDB.podspec
src/fmdb/FMDatabase.m

This will add a check to make sure we're connected to a SQCipher Database. Here is the [advisory](https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-8-and-new-sdks/1688) regarding the change.

Check that we are actually connected to an SQLCipher DB

---

FMDB.podspec

As far as I can see from other headers it's expected to use `#import <fmdb/FMDB.h>`, and **not** `#import <FMDB/FMDB.h>`.
https://github.com/ccgus/fmdb/blob/9a98636848905f48b6b9a304f2b90f9b3c2c9c4a/src/extra/fts3/FMDatabase%2BFTS3.h#L9
In some cases current podspec may not work as expected. This change will ensure the consistency in directory name register.
Related to #630

Fix header_dir path in podspec

---

CHANGES_AND_TODO_LIST.txt
README.markdown
Tests/FMDatabaseTests.m
src/extra/InMemoryOnDiskIO/FMDatabase+InMemoryOnDiskIO.h
src/extra/InMemoryOnDiskIO/FMDatabase+InMemoryOnDiskIO.m
src/fmdb/FMDatabase.h
src/fmdb/FMDatabase.m
src/fmdb/FMDatabaseAdditions.h
src/fmdb/FMDatabaseAdditions.m
src/fmdb/FMResultSet.h
src/fmdb/FMResultSet.m

* Allow re-binding of SQLite statements
- Reduced `executeUpdate` to call `executeQuery` and remove redundant code;
- Abstracted binding code out of from `executeQuery`;
- Created “prepare” method on `FMDatabase` (that prepares statement but doesn’t bind anything);
- Created “bind” methods on `FMResultSet` to bind values; and
- Created unit tests for both array and dictionary parameter types; each tests both update queries and select queries.
Usage:
For execute queries:
```
FMResultSet *rs = [db prepare:@"INSERT INTO foo (bar) VALUES (?)"];
if ([rs bindWithArray:@[value1]]) {
if ([rs step]) {
// successful
}
}
if ([rs bindWithArray:@[value2]]) {
if ([rs step]) {
// successful
}
}
```
While it’s most useful for `INSERT` and `UPDATE` queries, you can theoretically use it for select queries, …

Allow rebinding

---

src/fmdb/FMDatabaseQueue.m

I can’t imagine that anyone is using manual referencing counting any more, but there was an uninitialized pointer. 
Turns out that `blockError` reference is not needed, anyway, so let’s cut the Gordian knot.

Uninitialized object in manual reference counting

---

src/extra/fts3/FMDatabase+FTS3.h
src/extra/fts3/FMTokenizers.h
src/fmdb/FMDatabase.h
src/fmdb/FMDatabase.m
src/fmdb/FMDatabaseAdditions.h
src/fmdb/FMDatabasePool.h
src/fmdb/FMDatabaseQueue.h
src/fmdb/FMResultSet.h

I noticed that the inline documentation, which was tailored for appledoc, didn’t render well within Xcode. For example, the documentation for `FMDatabaseQueue` looked like:
With this PR, it is now rendered like so:
Bottom line, I’ve wrapped code blocks with `@code`/`@endcode`, replaced back ticks with `@c` tags, etc. I’ve also fixed some problems (e.g. a `#pragma` between the comment and the `@interface` was preventing documentation from showing up; a private method that shouldn’t have been exposed has been hidden; etc.).
In full disclosure, I didn’t do much review of the content of the documentation, but focused largely on the formatting only. Also, this was a fairly cursory cleanup and I’m sure it’s not perfect, but it’s much better, IMHO.
Assuming you’re good with these fixes, I’d …

Update header comments & documentation

---

README.markdown

We recently discovered _sqlite3DbMallocRawNN crash, MACH_Exception EXC_BAD_ACCESS KERN_INVALID_ADDRESS fault_address:0x3037646236307474. 
And we find a commit: 7da3c812cdddd6f5da1df31e7751ef3e56dacd6b. This commit update documentation for FMResultSet.
I suggest to update example code for FMResultSet. If the user did not read the newest documentation, they can read example code and avoid making mistakes.

Update example code for FMResultSet

---

CHANGES_AND_TODO_LIST.txt
FMDB.podspec
README.markdown
Tests/FMDatabaseTests.m
Tests/FMResultSetTests.m
fmdb.xcodeproj/project.pbxproj
fmdb.xcodeproj/xcshareddata/xcschemes/FMDB MacOS.xcscheme
fmdb.xcodeproj/xcshareddata/xcschemes/FMDB iOS.xcscheme
fmdb.xcodeproj/xcshareddata/xcschemes/FMDB watchOS.xcscheme
src/fmdb/FMDatabase.h
src/fmdb/FMDatabase.m
src/fmdb/FMResultSet.h
src/fmdb/FMResultSet.m
src/fmdb/Info.plist

* Add `typeForColumn` and `typeForColumnIndex` methods and tests
* Update warnings in `dataForColumn` and `dataForColumnIndex` to describe SQLite behavior re zero-length blobs
* Bump version to 2.7.8
This should permit accurate handling of zero-length BLOBs, as discussed in #73.
So, for example, if you want to delineate between NULL and a zero length BLOB, in Swift:
```swift
let fileURL = URL(fileURLWithPath: NSTemporaryDirectory())
.appendingPathComponent("test.sqlite")
do {
let db = FMDatabase(url: fileURL)
db.open()
try db.executeUpdate("CREATE TABLE test (data BLOB)", values: nil)
let data = "foo".data(using: .utf8)!
let sql = "INSERT INTO test (data) VALUES (?)"
try db.executeUpdate(sql, values: [data])
try db.executeUpdate(sql, values: [Data()])
try db.executeUpdate(sql, values: …
```

Add typeForColumn functions

---

FMDB.podspec

iOS min 11, macOS min 10.13, watchOS min 7.0.
Should fix: https://github.com/ccgus/fmdb/issues/844

Ups podspec min versions for modern xcode (xcode 14.3.x)

---

CHANGES_AND_TODO_LIST.txt
CONTRIBUTORS.txt
FMDB.podspec
Package.swift
README.markdown
Tests/FMDatabaseTests.m
src/fmdb/FMDatabase.h
src/fmdb/FMDatabase.m

After pushing the 2.7.11 release to CocoaPods trunk, the CocoaPods installation method is broken for people who use the following library subspec:
`FMDB/SQLCipher`
The issue is seen only when archiving an application for release, which fails because both the FMDB/SQLCipher subspec and SQLCipher dependency are including a Resource Bundle with the same name ("SQLCipher"). Below is the error output from xcodebuild:
`error: Multiple commands produce '.../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SQLCipher.bundle'
note: Target 'FMDB-SQLCipher' (project 'Pods') has create directory command with output '.../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SQLCipher.bundle'
note: Target 'SQLCipher-SQLCipher' (project 'Pods') has create directory command with output …

[URGENT] Fix CocoaPods and Swift Package Manager Installation Methods
